development:
  adapter: postgresql
  encoding: unicode
  database: singers_app_development
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: singers_app_production
  pool: 2
